name: imin_printer
description: It is used to print text, pictures, two-dimensional code, bar code and other functions sdk in imin printer using Android system
version: 0.7.0
homepage: https://github.com/iminsoftware/imin_printer

environment:
  sdk: '>=3.0.6 <4.0.0' 
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.imin.printer.imin_printer
        pluginClass: IminPrinterPlugin
