// import 'dart:typed_data';

import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:imin_printer/enums.dart';
import 'package:imin_printer/imin_printer.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:esc_pos_utils/esc_pos_utils.dart';
import 'package:imin_printer/imin_style.dart';
import 'package:imin_printer_example/pages/v2/info.dart';
import 'package:imin_printer_example/pages/v2/print_text_form.dart';

class NewHome extends StatefulWidget {
  const NewHome({super.key});
  final String title = '打印测试';
  @override
  State<NewHome> createState() => _NewHomeState();
}

class _NewHomeState extends State<NewHome> {
  final iminPrinter = IminPrinter();

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        // backgroundColor: Colors.transparent,
        appBar: AppBar(
          title: const Text(
            'v2 Print Test',
            // style: TextStyle(
            //     color: Color(0xFF1D1D1F), fontWeight: FontWeight.w600),
          ),
          elevation: 0,
          // backgroundColor: Colors.transparent,
        ),
        body: SingleChildScrollView(
            child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Wrap(
            direction: Axis.horizontal,
            spacing: 15,
            runSpacing: 10,
            alignment: WrapAlignment.start,
            children: [
              OutlinedButton(
                  onPressed: () async {
                    await iminPrinter.initPrinter();
                  },
                  child: const Text('init Printer')),
              OutlinedButton(
                  onPressed: () async {
                    String? state = await iminPrinter.getPrinterStatus();
                    Fluttertoast.showToast(
                        msg: state ?? '',
                        toastLength: Toast.LENGTH_LONG,
                        gravity: ToastGravity.BOTTOM, // 消息框弹出的位置
                        // timeInSecForIos: 1,  // 消息框持续的时间（目前的版本只有ios有效）
                        backgroundColor: Colors.red,
                        textColor: Colors.white,
                        fontSize: 16.0);
                  },
                  child: const Text('printer Status')),
              OutlinedButton(
                onPressed: () async {
                  await iminPrinter.resetDevice();
                },
                child: const Text('reset printer'),
              ),
              OutlinedButton(
                onPressed: () async {
                  await iminPrinter.unBindService();
                },
                child: const Text('unbind printer'),
              ),
              OutlinedButton(
                onPressed: () async {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) =>
                            const InfoPage(type: 'Printer Info')),
                  );
                },
                child: const Text('printer info'),
              ),
              OutlinedButton(
                onPressed: () async {
                  await iminPrinter.openCashBox();
                },
                child: const Text('open CashBox'),
              ),
              OutlinedButton(
                onPressed: () async {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) =>
                            const InfoPage(type: 'CashBox Info')),
                  );
                },
                child: const Text('cashBox info'),
              ),
              OutlinedButton(
                onPressed: () async {
                  await iminPrinter.printerSelfChecking();
                },
                child: const Text('print Self Checking'),
              ),
              OutlinedButton(
                onPressed: () async {
                  // final List<int> escPos = await customEscPos();
                  final List<int> escPos = [
                    0x1b,
                    0x40,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x11,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1b,
                    0x45,
                    0x01,
                    0x1b,
                    0x47,
                    0x01,
                    0xb1,
                    0xbe,
                    0xb5,
                    0xea,
                    0xc1,
                    0xf4,
                    0xb4,
                    0xe6,
                    0x0a,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x0a,
                    0x1b,
                    0x40,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x11,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1b,
                    0x45,
                    0x01,
                    0x1b,
                    0x47,
                    0x01,
                    0x1b,
                    0x61,
                    0x01,
                    0x23,
                    0x31,
                    0x35,
                    0x20,
                    0xb0,
                    0xd9,
                    0xb6,
                    0xc8,
                    0xcd,
                    0xe2,
                    0xc2,
                    0xf4,
                    0x0a,
                    0x5b,
                    0xbb,
                    0xf5,
                    0xb5,
                    0xbd,
                    0xb8,
                    0xb6,
                    0xbf,
                    0xee,
                    0x5d,
                    0x0a,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x0a,
                    0x1b,
                    0x40,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x01,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0xc6,
                    0xda,
                    0xcd,
                    0xfb,
                    0xcb,
                    0xcd,
                    0xb4,
                    0xef,
                    0xca,
                    0xb1,
                    0xbc,
                    0xe4,
                    0xa3,
                    0xba,
                    0xc1,
                    0xa2,
                    0xbc,
                    0xb4,
                    0xc5,
                    0xe4,
                    0xcb,
                    0xcd,
                    0x0a,
                    0xb6,
                    0xa9,
                    0xb5,
                    0xa5,
                    0xb1,
                    0xb8,
                    0xd7,
                    0xa2,
                    0xa3,
                    0xba,
                    0xc7,
                    0xeb,
                    0xcb,
                    0xcd,
                    0xb5,
                    0xbd,
                    0xbf,
                    0xfc,
                    0xbf,
                    0xc6,
                    0xce,
                    0xf7,
                    0xc3,
                    0xc5,
                    0x2c,
                    0xb2,
                    0xbb,
                    0xd2,
                    0xaa,
                    0xc0,
                    0xb1,
                    0x0a,
                    0xb7,
                    0xa2,
                    0xc6,
                    0xb1,
                    0xd0,
                    0xc5,
                    0xcf,
                    0xa2,
                    0xa3,
                    0xba,
                    0xb0,
                    0xd9,
                    0xb6,
                    0xc8,
                    0xcd,
                    0xe2,
                    0xc2,
                    0xf4,
                    0xb7,
                    0xa2,
                    0xc6,
                    0xb1,
                    0x0a,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x0a,
                    0x1b,
                    0x40,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0xb6,
                    0xa9,
                    0xb5,
                    0xa5,
                    0xb1,
                    0xe0,
                    0xba,
                    0xc5,
                    0xa3,
                    0xba,
                    0x31,
                    0x34,
                    0x31,
                    0x38,
                    0x37,
                    0x31,
                    0x38,
                    0x36,
                    0x39,
                    0x31,
                    0x31,
                    0x36,
                    0x38,
                    0x39,
                    0x0a,
                    0xcf,
                    0xc2,
                    0xb5,
                    0xa5,
                    0xca,
                    0xb1,
                    0xbc,
                    0xe4,
                    0xa3,
                    0xba,
                    0x32,
                    0x30,
                    0x31,
                    0x34,
                    0x2d,
                    0x31,
                    0x32,
                    0x2d,
                    0x31,
                    0x36,
                    0x20,
                    0x31,
                    0x36,
                    0x3a,
                    0x33,
                    0x31,
                    0x0a,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x0a,
                    0x1b,
                    0x40,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x01,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0xb2,
                    0xcb,
                    0xc6,
                    0xb7,
                    0xc3,
                    0xfb,
                    0xb3,
                    0xc6,
                    0x20,
                    0x20,
                    0x20,
                    0x20,
                    0x20,
                    0x20,
                    0x20,
                    0x20,
                    0x20,
                    0xca,
                    0xfd,
                    0xc1,
                    0xbf,
                    0x20,
                    0x20,
                    0x20,
                    0x20,
                    0x20,
                    0xbd,
                    0xf0,
                    0xb6,
                    0xee,
                    0x0a,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x0a,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x01,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0xcf,
                    0xe3,
                    0xc0,
                    0xb1,
                    0xc3,
                    0xe6,
                    0xcc,
                    0xd7,
                    0xb2,
                    0xcd,
                    0x1b,
                    0x24,
                    0xf2,
                    0x00,
                    0x31,
                    0x1b,
                    0x24,
                    0x25,
                    0x01,
                    0xa3,
                    0xa4,
                    0x34,
                    0x30,
                    0x2e,
                    0x30,
                    0x30,
                    0x0a,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x01,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0xcb,
                    0xd8,
                    0xca,
                    0xb3,
                    0xcc,
                    0xec,
                    0xcf,
                    0xc2,
                    0xba,
                    0xba,
                    0xb1,
                    0xa4,
                    0x1b,
                    0x24,
                    0xf2,
                    0x00,
                    0x31,
                    0x1b,
                    0x24,
                    0x25,
                    0x01,
                    0xa3,
                    0xa4,
                    0x33,
                    0x38,
                    0x2e,
                    0x30,
                    0x30,
                    0x0a,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1b,
                    0x40,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x2d,
                    0x0a,
                    0x1b,
                    0x40,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x0a,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x01,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0xd0,
                    0xd5,
                    0xc3,
                    0xfb,
                    0xa3,
                    0xba,
                    0xb0,
                    0xd9,
                    0xb6,
                    0xc8,
                    0xb2,
                    0xe2,
                    0xca,
                    0xd4,
                    0x0a,
                    0xb5,
                    0xd8,
                    0xd6,
                    0xb7,
                    0xa3,
                    0xba,
                    0xbf,
                    0xfc,
                    0xbf,
                    0xc6,
                    0xbf,
                    0xc6,
                    0xbc,
                    0xbc,
                    0xb4,
                    0xf3,
                    0xcf,
                    0xc3,
                    0x0a,
                    0xb5,
                    0xe7,
                    0xbb,
                    0xb0,
                    0xa3,
                    0xba,
                    0x31,
                    0x38,
                    0x37,
                    0x30,
                    0x30,
                    0x30,
                    0x30,
                    0x30,
                    0x30,
                    0x30,
                    0x30,
                    0x0a,
                    0x1b,
                    0x40,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x0a,
                    0xb0,
                    0xd9,
                    0xb6,
                    0xc8,
                    0xb2,
                    0xe2,
                    0xca,
                    0xd4,
                    0xc9,
                    0xcc,
                    0xbb,
                    0xa7,
                    0x0a,
                    0x31,
                    0x38,
                    0x37,
                    0x30,
                    0x30,
                    0x30,
                    0x30,
                    0x30,
                    0x30,
                    0x30,
                    0x0a,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x2a,
                    0x0a,
                    0x1b,
                    0x4d,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1d,
                    0x21,
                    0x00,
                    0x1b,
                    0x45,
                    0x00,
                    0x1b,
                    0x47,
                    0x00,
                    0x1b,
                    0x61,
                    0x00,
                    0x1b,
                    0x61,
                    0x01,
                    0x23,
                    0x31,
                    0x35,
                    0x20,
                    0xb0,
                    0xd9,
                    0xb6,
                    0xc8,
                    0xcd,
                    0xe2,
                    0xc2,
                    0xf4,
                    0x20,
                    0x20,
                    0x31,
                    0x31,
                    0xd4,
                    0xc2,
                    0x30,
                    0x39,
                    0xc8,
                    0xd5,
                    0x20,
                    0x31,
                    0x37,
                    0x3a,
                    0x35,
                    0x30,
                    0x3a,
                    0x33,
                    0x30,
                    0x0a,
                    0x0a,
                    0x0a,
                    0x0a,
                    0x0a
                  ];
                  debugPrint('escPos: $escPos');

                  await iminPrinter.sendRAWData(Uint8List.fromList(escPos));
                },
                child: const Text('sendRAWData'),
              ),
              OutlinedButton(
                onPressed: () async {
                  await iminPrinter.printAndLineFeed();
                },
                child: const Text('printAndLineFeed'),
              ),
              OutlinedButton(
                onPressed: () async {
                  await iminPrinter.printAndFeedPaper(70);
                },
                child: const Text('printAndFeedPaper'),
              ),
              OutlinedButton(
                onPressed: () async {
                  await iminPrinter.partialCut();
                },
                child: const Text('partialCut'),
              ),
              OutlinedButton(
                onPressed: () async {
                  await iminPrinter.setCodeAlignment(IminPrintAlign.center);
                },
                child: const Text('setCodeAlignment'),
              ),
              OutlinedButton(
                onPressed: () async {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) => const PrintTextSettingPage(
                            type: 'Printer Text Setting')),
                  );
                  // await iminPrinter.printTextBitmap('iMin advocates the core values of "Integrity, Customer First, Invention&Creation, Patience”, using cloud-based technology to help businesses to get  access to the Internet and also increases their data base, by providing more solutions so that their business can take a step further. Through their efficiency enhancement, cost improvement, service innovation, and  better services for consumers, these aspect will drives the entire industry development.', style: IminTextPictureStyle(wordWrap: true, reverseWhite: true));
                },
                child: const Text('printTextBitmap'),
              ),
              OutlinedButton(
                onPressed: () async {
                  // Uint8List byte =
                  //     await readFileBytes('assets/images/logo.png');
                  // await iminPrinter.printSingleBitmap(byte,
                  //     pictureStyle: IminPictureStyle(
                  //       alignment: IminPrintAlign.center,
                  //       width: 50,
                  //       height: 20,
                  //     ));

                  await iminPrinter.printSingleBitmap(
                      'https://oss-sg.imin.sg/web/iMinPartner2/images/logo.png',
                      pictureStyle: IminPictureStyle(
                        alignment: IminPrintAlign.right,
                        width: 150,
                        height: 50,
                      ));
                },
                child: const Text('print singleBitmap'),
              ),
              OutlinedButton(
                onPressed: () async {
                  // Uint8List byte1 =
                  //     await _getImageFromAsset('assets/images/logo.png');
                  // Uint8List byte2 =
                  //     await _getImageFromAsset('assets/images/logo.png');

                  // await iminPrinter.printMultiBitmap([byte1, byte2],
                  //     pictureStyle: IminPictureStyle(
                  //         alignment: IminPrintAlign.left));
                  await iminPrinter.printMultiBitmap([
                    'https://oss-sg.imin.sg/web/iMinPartner2/images/logo.png',
                    'https://oss-sg.imin.sg/web/iMinPartner2/images/logo.png'
                  ],
                      pictureStyle: IminPictureStyle(
                        alignment: IminPrintAlign.left,
                        width: 250,
                        height: 30,
                      ));
                },
                child: const Text('print multiBitmap'),
              ),
            ],
          ),
        )));
  }
}

Future<List<int>> customEscPos() async {
  final profile = await CapabilityProfile.load();
  final generator = Generator(PaperSize.mm58, profile);
  List<int> bytes = [];

  bytes += generator.text(
      'Regular: aA bB cC dD eE fF gG hH iI jJ kK lL mM nN oO pP qQ rR sS tT uU vV wW xX yY zZ');
  bytes += generator.text('Special 1: àÀ èÈ éÉ ûÛ üÜ çÇ ôÔ',
      styles: const PosStyles(codeTable: 'CP1252'));
  bytes += generator.text('Bold text', styles: const PosStyles(bold: true));
  bytes +=
      generator.text('Reverse text', styles: const PosStyles(reverse: true));
  bytes += generator.text('Underlined text',
      styles: const PosStyles(underline: true), linesAfter: 1);
  bytes += generator.text('Align left',
      styles: const PosStyles(align: PosAlign.left));
  bytes += generator.text('Align center',
      styles: const PosStyles(align: PosAlign.center));
  bytes += generator.text('Align right',
      styles: const PosStyles(align: PosAlign.right), linesAfter: 1);
  bytes += generator.qrcode('Barcode by escpos',
      size: QRSize.Size4, cor: QRCorrection.H);
  bytes += generator.feed(2);
  bytes += generator.row([
    PosColumn(
      text: 'col3',
      width: 3,
      styles: const PosStyles(align: PosAlign.center, underline: true),
    ),
    PosColumn(
      text: 'col6',
      width: 6,
      styles: const PosStyles(align: PosAlign.center, underline: true),
    ),
    PosColumn(
      text: 'col3',
      width: 3,
      styles: const PosStyles(align: PosAlign.center, underline: true),
    ),
  ]);
  bytes += generator.text('Text size 200%',
      styles: const PosStyles(
        height: PosTextSize.size2,
        width: PosTextSize.size2,
      ));

  bytes += generator.reset();
  bytes += generator.cut();
  return bytes;
}
